apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
spec:
  containers:
    - name: postgres
      image: quay.io/fedora/postgresql-16:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5432
          hostPort: 5432
      env:
        - name: POSTGRESQL_USER
          value: "podman"
        - name: POSTGRESQL_PASSWORD
          value: "podman"
        - name: POSTGRESQL_DATABASE
          value: "reportflow"
      resources:
        limits:
          cpu: "1"     
          memory: "2Gi" 
        requests:
          cpu: "500m"
          memory: "1Gi"
