version: "3"

env:
  ENV: "{{default \"dev\" .ENV}}"

dotenv: [".env/{{.ENV}}"]

tasks:
  greet:
    cmds:
      - echo "Using {{.KEYNAME}} and endpoint {{.ENDPOINT}}"

  publishLocal:
    cmds:
      - sbt 'server / Docker / publishLocal'

  publish:
    cmd:
      - sbt 'server / Docker / publish'
  