apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: reportflow-kustomization
  namespace: myapp
resources:
  - namespace.yaml
  - postgresql.yaml
  - postgresql-svc.yaml
  - reportflow.yaml
  - reportflow-svc.yaml
