apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportflow-deployment
spec:
  selector:
    matchLabels:
      app: reportflow
  template:
    metadata:
      labels:
        app: reportflow
    spec:
      containers:
        - name: reportflow
          image: quay.io/nestor9001/reportflow:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_JDBC_URL
              value: "jdbc:postgresql://postgresql-svc:5432/reportflow"
            - name: DATABASE_USER
              value: docker
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secrets
                  key: POSTGRES_PASSWORD
